/*GENERATED BY OBNC 0.16.1*/

#include ".obnc/Bitwise.h"
#include <obnc/OBNC.h>

#define OBERON_SOURCE_FILENAME "Bitwise.mod"

OBNC_INTEGER Bitwise__And_(OBNC_INTEGER a_, OBNC_INTEGER b_)
{
	return a_ & b_;
}


OBNC_INTEGER Bitwise__Or_(OBNC_INTEGER a_, OBNC_INTEGER b_)
{
	return a_ | b_;
}


OBNC_INTEGER Bitwise__Not_(OBNC_INTEGER a_)
{
	return ~a_;
}


void Bitwise__Init(void)
{
}
