/*GENERATED BY OBNC 0.16.1*/

#ifndef Bitwise_h
#define Bitwise_h

#include <obnc/OBNC.h>

#define Bitwise__And_ obncext__Bitwise__And_
OBNC_INTEGER Bitwise__And_(OBNC_INTEGER a_, OBNC_INTEGER b_);

#define Bitwise__Or_ obncext__Bitwise__Or_
OBNC_INTEGER Bitwise__Or_(OBNC_INTEGER a_, OBNC_INTEGER b_);

#define Bitwise__Not_ obncext__Bitwise__Not_
OBNC_INTEGER Bitwise__Not_(OBNC_INTEGER a_);

#define Bitwise__Init obncext__Bitwise__Init
void Bitwise__Init(void);

#endif
